### ISSUE TITLE
建议：暗色模式列表需要默认除去几个包名

### ISSUE THREAD

**Issue by TayLin99** [AzukiAtsui/ColorOS_Mod#4]
com.eg.android.AlipayGphone
com.tencent.mm
com.unionpay
com.tencent.mobileqq

这几个包名分别是支付宝、微信、云闪付、QQ
暗色模式最好默认除去这几个应用包名，目前发现 付款码 界面会因为暗色模式导致反色，以至于扫码机器无法识别该付款码。

**Comment by TayLin99** [comment]
com.android.launcher
系统桌面的包名，也需要加入黑名单

目前发现会导致桌面小部件异常变色

**Comment by AzukiAtsui** [comment]
系统应用不被加入，自行检查设置



---Original---
From: ***@***.***&gt;
Sent at: 2022年10月28日(Fri) AM10:12
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [AzukiAtsui/ColorOS_Mod] 建议：暗色模式列表需要默认除去几个包名 (Issue #4)




 
com.android.launcher
 系统桌面的包名，也需要加入黑名单
 
目前发现会导致桌面小部件异常变色
